postgres:
  user: foo
  password: bar
  host: 127.0.0.1
  port: 5432
  db: dev

s3:
  host: 127.0.0.1
  port: 9000
  access_key: foo
  secret_key: bar
  ssl: false
  buckets:
    - name: dev
      region: us-east-1
      lock: false

kafka:
  brokers:
    - host: 127.0.0.1
      port: 9091
  topics:
