// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoProcessingServiceClient is the client API for VideoProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoProcessingServiceClient interface {
	StartProcessing(ctx context.Context, in *StartProcessingRequest, opts ...grpc.CallOption) (*StartProcessingResponse, error)
	GetProcessingStatus(ctx context.Context, in *ProcessIdRequest, opts ...grpc.CallOption) (*GetProcessingStatusResponse, error)
	GetProcessingResult(ctx context.Context, in *ProcessResultRequest, opts ...grpc.CallOption) (*GetProcessingResultResponse, error)
	StopProcessing(ctx context.Context, in *ProcessIdRequest, opts ...grpc.CallOption) (*StopProcessingResponse, error)
}

type videoProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoProcessingServiceClient(cc grpc.ClientConnInterface) VideoProcessingServiceClient {
	return &videoProcessingServiceClient{cc}
}

func (c *videoProcessingServiceClient) StartProcessing(ctx context.Context, in *StartProcessingRequest, opts ...grpc.CallOption) (*StartProcessingResponse, error) {
	out := new(StartProcessingResponse)
	err := c.cc.Invoke(ctx, "/VideoProcessingService/StartProcessing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoProcessingServiceClient) GetProcessingStatus(ctx context.Context, in *ProcessIdRequest, opts ...grpc.CallOption) (*GetProcessingStatusResponse, error) {
	out := new(GetProcessingStatusResponse)
	err := c.cc.Invoke(ctx, "/VideoProcessingService/GetProcessingStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoProcessingServiceClient) GetProcessingResult(ctx context.Context, in *ProcessResultRequest, opts ...grpc.CallOption) (*GetProcessingResultResponse, error) {
	out := new(GetProcessingResultResponse)
	err := c.cc.Invoke(ctx, "/VideoProcessingService/GetProcessingResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoProcessingServiceClient) StopProcessing(ctx context.Context, in *ProcessIdRequest, opts ...grpc.CallOption) (*StopProcessingResponse, error) {
	out := new(StopProcessingResponse)
	err := c.cc.Invoke(ctx, "/VideoProcessingService/StopProcessing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoProcessingServiceServer is the server API for VideoProcessingService service.
// All implementations must embed UnimplementedVideoProcessingServiceServer
// for forward compatibility
type VideoProcessingServiceServer interface {
	StartProcessing(context.Context, *StartProcessingRequest) (*StartProcessingResponse, error)
	GetProcessingStatus(context.Context, *ProcessIdRequest) (*GetProcessingStatusResponse, error)
	GetProcessingResult(context.Context, *ProcessResultRequest) (*GetProcessingResultResponse, error)
	StopProcessing(context.Context, *ProcessIdRequest) (*StopProcessingResponse, error)
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

// UnimplementedVideoProcessingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVideoProcessingServiceServer struct {
}

func (UnimplementedVideoProcessingServiceServer) StartProcessing(context.Context, *StartProcessingRequest) (*StartProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcessing not implemented")
}
func (UnimplementedVideoProcessingServiceServer) GetProcessingStatus(context.Context, *ProcessIdRequest) (*GetProcessingStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessingStatus not implemented")
}
func (UnimplementedVideoProcessingServiceServer) GetProcessingResult(context.Context, *ProcessResultRequest) (*GetProcessingResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessingResult not implemented")
}
func (UnimplementedVideoProcessingServiceServer) StopProcessing(context.Context, *ProcessIdRequest) (*StopProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProcessing not implemented")
}
func (UnimplementedVideoProcessingServiceServer) mustEmbedUnimplementedVideoProcessingServiceServer() {
}

// UnsafeVideoProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoProcessingServiceServer will
// result in compilation errors.
type UnsafeVideoProcessingServiceServer interface {
	mustEmbedUnimplementedVideoProcessingServiceServer()
}

func RegisterVideoProcessingServiceServer(s grpc.ServiceRegistrar, srv VideoProcessingServiceServer) {
	s.RegisterService(&VideoProcessingService_ServiceDesc, srv)
}

func _VideoProcessingService_StartProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).StartProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VideoProcessingService/StartProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).StartProcessing(ctx, req.(*StartProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoProcessingService_GetProcessingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).GetProcessingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VideoProcessingService/GetProcessingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).GetProcessingStatus(ctx, req.(*ProcessIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoProcessingService_GetProcessingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).GetProcessingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VideoProcessingService/GetProcessingResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).GetProcessingResult(ctx, req.(*ProcessResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoProcessingService_StopProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoProcessingServiceServer).StopProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VideoProcessingService/StopProcessing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoProcessingServiceServer).StopProcessing(ctx, req.(*ProcessIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoProcessingService_ServiceDesc is the grpc.ServiceDesc for VideoProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VideoProcessingService",
	HandlerType: (*VideoProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcessing",
			Handler:    _VideoProcessingService_StartProcessing_Handler,
		},
		{
			MethodName: "GetProcessingStatus",
			Handler:    _VideoProcessingService_GetProcessingStatus_Handler,
		},
		{
			MethodName: "GetProcessingResult",
			Handler:    _VideoProcessingService_GetProcessingResult_Handler,
		},
		{
			MethodName: "StopProcessing",
			Handler:    _VideoProcessingService_StopProcessing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
